
name: build-wheels

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-wheels:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64

    steps:
    - uses: actions/checkout@v2

    # - name: Install bazel
    #   run:  |
    #         apt-get update
    #         apt-get install -yq software-properties-common
    #         add-apt-repository ppa:deadsnakes/ppa
    #         apt-get update
    #         apt-get install -yq python3.7
    #         apt-get install -yq wget gcc g++ zlib1g-dev zip libuv1.dev
    #         apt-get install -yq pip
    #         wget "https://github.com/bazelbuild/bazel/releases/download/5.1.0/bazel_5.1.0-linux-x86_64.deb" -O bazel_5.1.0-linux-x86_64.deb
    #         dpkg -i bazel_5.1.0-linux-x86_64.deb


    - name: Build wheels
      run: |
           bash build_wheels.sh
    
    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        path: ./dist/*.whl